version: '3.8'

services:
  # 0️⃣ .env.example → .env kopyalayıcı servis (sadece ilk çalıştırmada çalışır)
  copy-env:
    image: alpine
    restart: "no"
    volumes:
      - .:/app                      # Proje klasörünü container içine mount ediyoruz
    working_dir: /app
    command: >
      sh -c "
        if [ ! -f .env ]; then
          cp .env.example .env && echo '.env oluşturuldu';
        else
          echo '.env zaten var';
        fi
      "

  # 1️⃣ NGINX Reverse Proxy (80/443 yerine özel portlar: 8080, 8443)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"                  # Host 8080 → Container 80 (HTTP)
      - "8443:443"                 # Host 8443 → Container 443 (HTTPS)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - copy-env
      - app
      - webhook

  # 2️⃣ MySQL Veritabanı Servisi
  mysql:
    image: mysql:8
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER:     ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    depends_on:
      - copy-env

  # 3️⃣ App Servisi (FastAPI olabilir)
  app:
    build: ./app
    env_file: .env
    depends_on:
      - copy-env
      - mysql

  # 4️⃣ Webhook Servisi (Flask, Instagram mesajları için webhook endpoint)
  webhook:
    build: ./webhook
    env_file: .env
    depends_on:
      - copy-env
      - mysql

volumes:
  db_data:  # MySQL verisi için kalıcı volume
